# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    storage.fonts.path: '%kernel.project_dir%/storage/fonts'
    storage.media.path: '%kernel.project_dir%/storage/media'

services:
    font_storage.adapter:
        class: League\Flysystem\Local\LocalFilesystemAdapter
        arguments:
            $location: '%storage.fonts.path%'

    font_storage.filesystem:
        class: League\Flysystem\Filesystem
        arguments:
            $adapter: '@font_storage.adapter'

    League\Flysystem\FilesystemOperator:
        alias: font_storage.filesystem

    media_storage.adapter:
        class: League\Flysystem\Local\LocalFilesystemAdapter
        arguments:
            $location: '%storage.media.path%'

    media_storage.filesystem:
        class: League\Flysystem\Filesystem
        arguments:
            $adapter: '@media_storage.adapter'

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'

    # Surcharges : arguments non autowirés (doivent être après App\ pour remplacer)
    App\Service\FontStorage:
        arguments:
            $filesystem: '@font_storage.filesystem'

    App\Service\MediaStorage:
        arguments:
            $filesystem: '@media_storage.filesystem'

    App\Service\ThemeCssGenerator:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Controller\ThemeController:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\EventListener\DisableProfilerOnMediaUploadListener:
        arguments:
            $profiler: '@?profiler'
